{% set name = "anaconda-catalogs" %}
{% set version = "0.2.0" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f9396ced850ec377fd6ef0d9be43bb6f62dd0a61da69582d077458e3bb12e7d

build:
  number: 2
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - toml
    - wheel
  run:
    - python
    - aiohttp
    - intake
    - requests
    - jinja2 # extra needed by intake for catalogs utils

test:
  source_files:
    - tests
  imports:
    - anaconda_catalogs
  requires:
    - pytest
  commands:
    - pytest

about:
  home: https://github.com/anaconda/anaconda-cloud-tools
  dev_url: https://github.com/anaconda/anaconda-cloud-tools
  doc_url: https://github.com/anaconda/anaconda-cloud-tools
  summary: Client library to interface with Anaconda Cloud catalogs service
  description: |
    Client library to interface with Anaconda Cloud catalogs service
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
  skip-lints:
    - missing_pip_check
